# reusing CI infrastructure from conda-forge
# see https://conda-forge.org/docs/user/ci-skeleton.html

clone_depth: 0
recipe_dir: conda.recipe
skip_render:
  - README.md
  - LICENSE.txt
  - .gitattributes
  - .gitignore
  - build-locally.py
  - LICENSE
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows
