channel_targets:
    - tsnyder main


# define a set of twisted versions to test against
# started from what was relased in mid-2019 because danielinux
# said he had it working in November 2019
twisted:
    - 19.*
    - 20.*
    - 21.*
    - 22.*
zope.interface:
    - 4.6.*
    - 4.7.*
    - 5.0.*
    - 5.1.*
    - 5.2.*
    - 5.3.*
    - 5.4.*
pygraphviz:
    - 1.5.*
    - 1.6.*
    - 1.7.*
    # 1.8 was yanked from pypi
    - 1.9.*
python:
    - 3.6.* *_cpython
    - 3.7.* *_cpython
    - 3.8.* *_cpython
    - 3.9.* *_cpython
    - 3.10.* *_cpython
# since the upstream conda-forge-pinning-feedstock
# uses python in zip-keys with numpy and python_impl
# we have to make sure that the lengths of those keys
# also match (and that 3.5 and 3.6 are set to an existing version
numpy:
    - 1.16
    - 1.19
    - 1.19
    - 1.19
    - 1.19

python_impl:
    - cpython
    - cpython
    - cpython
    - cpython
    - cpython
